[POZEKRANI]
PRGTYPE=Ercom
TEKNOLOJI=EGEPEN23
MARKA=Pimapen
SONFIRMA=EGEPEN23
muhuser=root
muhserver=server
muhdata=muhasebe
FABOTMUSER=root
FABOTMSERVER=server
FABOTMDATAANAMENU=uretim
CAMPATH=C:\CAM2000\
BINLIKSIMGE=,
ONDALIKSIMGE=.
excelyolu=C:\E2000\TEMP
AYRAC=;
KURUS=2
HataGoster=0
LAZER=0
BUTONYARDIM=1
FORMPATH=C:\Ercom\E2WIN\FORM\
FIRMAADIC=1
MUSID=4260
BASLIK=SÝSTEM YAPI ELEMANLARI - ASLIMLAR    
FIRMATEL=TEL: 90 332 812 39 95 - 812 83 57       
YEDEKYOL=C:\Ercom\E2WIN\TEMP
AKTARILAN=0
Pop3Port=4260
KULLANICI=e2000_mail
MailServer=www.ercom.net
GIDENMAIL=4260
AKTIFKOD=0
BAYIKODU=00-0000
CAMTUT=12
MONTUT=22,5
USERNAME= 
HANICNO=1
HANICKONTROL=0
SAYACKONTROL=0
EXCELRECETE=0
PROFILDETAY=1
KesitGoster=0
CNCISLEMPANEL=0
FIRELIDUS=0
POZAGORESTOKDUS=1
LAMBRIHESABI=1
EKSENKONTROL=1
AKSKONTROL=0
ACKAL=2
KAYITMONTAJ=1
DEFOLCEK=5
TAMKEMER=1
USTKANAT=1100
SAGKANAT=600
SOLKANAT=600
KESIMACI=0
SLEFT=235
STOP=1041
KANATCITAKAL=2
KANATICKAL=2
KASACITAKAL=2
KASAICKAL=2
BAGKAL=2
MARMARKAL=2
KASAKAL=3
CAMOLCU2=1
METRAJHESAPLAT=0
CAMTIPI=1
CAMGOSTER=1
SOLPANEL=1
USTPANEL=1
SURMESINEKLIKALM=1
SURMESINEKLIKPLS=1
SURGUESIT=1
ISLEMDEVAM=1
DLESIK=1
DLMENTESE=0
DLPANJUR=1
DL11=1
DL9=1
DL10=1
DL8=1
DL7=1
DL6=1
DL5=1
DL4=1
DL3=1
DL2=1
DL1=1
OPTIGRUP=1
USTBASLIK1=1
TRESUST=0
MLYUST=0
MERMERUST=0
SCAMSIPUST=0
RCAMSIPUST=0
IMLUST=0
CAMSIPUST=0
KOMBOKONTROL=4
KYATAYRENK=1
KYATAYSERI=0
ESIK90=0
ALTBASMAFARK=0
ESIKYUK=0
KASADUS=0
ALTBASMA=0
KDIKEYRENK=1
KDIKEYSERI=0
SAYFAALTTOPLAM=1
MONTAJYAZ=1
BUTUNPOZLAR1=0
BIRLESIK1=0
CAMOLCEK=0,5
CAMPOZ=1
CAMOLCUSU=1
SABLONILAVE=1
CAMBUTUNPOZLAR=1
BARCODEYAZ=0
SOLADAYALI=0
AKSMARKA=1
KNTIPI=1
DRA=60
YRA=75
YATAYYAZDIR=0
ESIKOLCUSU=1
SERIYAZ=1
PTIPI=0
POZCCAMTIPI=0
POZCAMOLCU=1
POZDISOLCU=1
POZARAOLCU=1
TYARDIMCIPROFIL=0
POZAGORESIRALA=1
ACILIYAZ=1
MONTAJYAZ1=1
BUTUNPOZLAR5=1
TKKEMER=1
TKKANAT=1
TKKAYIT=1
TKKASA=1
FIRELIHESAPANABOY=0
FIREYOKGRUP=180
FIREYOK=0
opsiyonel=0
FIRELIHESAP=0
OZELFIYAT1=1
ISCILIK=25
KDVM=20
BUTUNPOZLAR4=1
ANALIZ=1
BUTUNPOZLAR3=1
KANATRENK=1
KANATPROFIL=0
PERVAZKAYNAKPAYI=6
PERVAZADAPTOR=0
PERVAZKAYNAK=1
YATAYRENK=1
YATAYSERI=0
DIKEYSERI=0
DIKEYRENK=1
OPTIPARCA=1
TKASA=0
TC295EGONDER=0
TTYEGONDER=1
NR210AGONDER=0
MONTAJDELIGI=0
ISLEMLISTESI=1
VeriAktar=1
CEVIRMELIOPT=1
AYNISTOKOPT=1
ISOFORMNO=FRM.ÜR.13/15.02.08/00
FIRESAY=1
TESTERE2=5
TESTERE1=7
FAKTOR=100
TESTERE=4
EXCELALT=1
KAYNAKIPTAL=0
FIYATKONTROL=0
LAMBRIKONTROL=0
sskodudd=0
MONSTOKMTUL=MON01
MONSTOKM2=MON02
KANATTOPLA=1
KAYITTOPLA=1
KASATOPLA=1
STOKKODUYAZ=0
sonraRESIMYAZ=1
SAYFAUST=0
RESIMYAZ=1
FTODEMEPLANI=0
LISTEDETAY=1
DOGRAMAADET=1
DRA1=180
YRA1=180
OZELFIYAT2=0
ODEMEPLANI=0
FSERIYAZ=1
METRAJYAZ=0
TFIYAT=0
POZADET=1
TRACIKLAMA=0
CAMOLCU=1
DISOLCU=1
ARAOLCU=1
PANJURY=1000
PANJURHESAP=1
NAKLIYEHESAPLA=0
NAKSTOK=NK001
KDVKONTROL=1
FTDETAYLIHESAP=1
GRUPISKONTO=0
MONTAJHESAPLA=0
MONTAJKONTROL=1
RAPORNO=0
RKDVGYV=0
RDETAYINDEXV=0
pozFIYATDETAY=1
RESIMLIFIYATDETAY=1
RKDVY=0
RISKONTOY=0
RMONTAJY=0
EkMlz3="¸ÝP@
EkMlz2=Sökme Ýþçiliði
EkMlz1=INSURANCE
USTBASLIK=1
KDV=20
MONTAJHARIC=1
SIFIRBAKIYE=1
OTMCARIKOD=0
KAPASITEGUN=5
KOLBALANS=0
KOLYERITERS=0
KOSEKAYNAK=
KAYNAKYOL=C:\KD67
KANATPROFILLERI=1
KASAPROFILLERI=1
OYMAX=2600
OGMAX=3000
OYMIN=320
OGMIN=320
KAYNAKPAYI=1
CITAKESIM=1
TCITAPROFILLERI=0
KESIMADET=1
TKAYITPROFILLERI=1
TKANATPROFILLERI=1
TKASAPROFILLERI=1
TPERVAZ=0
MAKINASEC=2
CAMDATAYOLU=C:\
YATAYFARK=100
DIKEYFARK=100
MUHASEBEAKTAR=1
AKTIFLISAN=Native
SEVKGUN=7
MANUEL=A""33"35"36"37"38"39"40"41"42"43"44"45"46"47""A
HBSB=A""33"35"36"37"38"39"40"41"42"43"44"45"46"47""A
VT=A""90"91""101"102""A
VY=A""92"100""A
HOK=A""33"35"36"37"38"39"40"41"42"43"44"45"46"47""A
CACILIM=A""20"21"22"27"28"29""A
TACILIM=A""1"2"3"4"5"6"7"8"9"10"23"24"25"26""A
WCKAPI=A""67""A
ICKAPI=A""66""A
DISKAPI=A""65""A
KILITSIZISP=A""63"64""A
KILITLIISP=A""53"56"57"58"68"69"70"72"73"76"77"80"81"A
KDVORANI=18
MAILSIFRE=¬ywww{x{zq
SmtpPass=}}{|q
FABOTMPASS=qq
muhpass=qq
SAYFANO=1
ISIFORMUL=0
TIRNAKPAYIEKLE=1
KOLDETAY=0
MENTESEDETAY=0
RENKDETAY=0
CAMDETAY=0
AKSESUARDETAY=0
DESTEKPOZ=1
MLYTOPLAMAKTAR=1
PDFAc=0
PDFKaydet=1
PARCABIRAK=0
OPTBOYTOPLAT=0
MONTAJADI=
BDHESAPLA=1
BDSTOK=BCD01
IRSALIYEANAPARA=0
FYTTOPLAMAKTAR=1
AUTOCARI=1
SIPISKONTO=0
FLISTE=0
FIYAT=5
DOVIZ=0
PROFILHT=1
CAMHT=1
OLCEK=1291
MONTAJY=0
ISKONTOY=0
RENKSEC=0
DOVIZKURYAZ=1
MonitorDPI=100
DOVIZKURYAZF=1
FABOTMDATA=uretim
DLANARENK=1
DLDESTEK=0
YARDIMCIDETAY=1
MALIYETFIYAT=0
MALIYETLISTE=0
HESAPTIPI=0
HESAPSEKLI=0
MALIYETPARA=0
RENKSEC1=1
AKSESUARTAKIM=0
MATRIX=0
KONTROL10=
KONTROL9=
KONTROL8=
KONTROL7=
KONTROL6=
KONTROL5=
KONTROL4=
KONTROL3=
KONTROL2=
KONTROL1=1
STOK10=
STOK9=
STOK8=
STOK7=
STOK6=
STOK5=
STOK4=
STOK3=
STOK2=
STOK1=
RSATISORAN=26
FIRMAADRES=
PanelYol=C:\Ercom\E2Win\Panel\
ERPExcel=0
CHSIPTARIH=0
ERPSTOKAKTAR=0
MUHASEBEGRUP=0
KAPAKYAZDIR=0
MALIYETFIYATKAR=0
TMODEMEPLANI=1
CARIEKSTRETARIH=1
BAGKALINLIKYAZ=0
CIZGIYAZ=1
RESIMSAYISI=3
UWFIYATDETAY=0
STOKFIYATDETAY=0
RISKONTO2Y=0
POZALTTOPLAMAYRI=1
ACILANMENU=1
ALMDETAY=0
BACADELIGI=110
BACAKOORDINATYAZ=1
PANJURISCILIKKODU=PM001
PANJURISCILIK=1
JALUZICAM=1
BIRIMFIYATYAZ=1
ACILANMENUSK=1
TKHKAYIT=1
ARGONSTOK=ARG01
ISKONTO2Y=0
GenYukMax=4
RESIMOLUSTUR=1
CITAPOZ=0
UWHESAP=0
PANJURCIZGI=0
PRGID=20
#VAR=1
POZMUHASEBEAKTAR=0
TeklifRenk=
KESITYAZDIR=1
CAMM2YAZ=1
BARGEN=12
POZKG=1
FPOZKG=1
KGHesap=1
POZRESIM=1
MUHASEBECAMAKTAR=0
FPTIPI=0
CITADETAY=1
PROFILYAZDIR=0
MinFire=200
INCHYAZ=0
KESIMDUZELTME=20
KAROLCUGOSTER=1
BAGLANTIADAPTORU=20
CAMFARKI=20
INCHYAZP=0
VERSIYON=3,07
M2YAZ=0
